id: P008089
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159523
  title: ༢༠༡༡་ལོའི་བསྒྱུར་རྩོམ།
  author: ''
  volumes:
    06807dfa911c493094e29331e0616554:
      image_group_id: I2PD19015
      title: ''
      volume_number: 1
      total_pages: 298
ebook_metadata:
  title: ༢༠༡༡་ལོའི་བསྒྱུར་རྩོམ།
  author: ''
  sku: P008089
  cover: cover.jpg
  layers:
  - pagination
