id: P008089
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD159523
  title: ༢༠༡༡་ལོའི་བསྒྱུར་རྩོམ།
  author: ''
  volumes:
    46c3f0b6950741ef9e143069127bd8ea:
      image_group_id: I2PD19015
      title: Volume 1 of bsgyur rtsom/
      volume_number: 1
      total_pages: 298
      base_file: v001.txt
